# Generated by Django 3.0.4 on 2020-03-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('starting_bid', models.CharField(max_length=10, verbose_name='Starting bid')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('contact', models.CharField(max_length=13, verbose_name='Mobile Number')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
